### ISSUE TITLE
Why Template?

### ISSUE THREAD

**Issue by TheYoBots** [M-DinhHoangViet/Lichess-Bot#18]
https://stackoverflow.com/a/64058974

As per the above link:
> You are unable to push changes to the forked repository as well. Templates are intended to use a repository as-is.

I think many things like config, engine, etc... need to be edited in order to use this repository and it being a template makes no sense.

**Comment by M-DinhHoangViet** [comment]
There are some things I don't understand, can you clarify because my English is quite poor

**Comment by TheYoBots** [comment]
My question is, why is this repository a public template? It shouldn't be one.
